export const CONSTANT = {
    DATABASE_CONNECTION: 'DATABASE_CONNECTION',
    PHOTO_REPOSITORY: 'PHOTO_REPOSITORY',
    AUTHOR_REPOSITORY: 'AUTHOR_REPOSITORY',
    PHOTO_METADATA_REPOSITORY: 'PHOTO_METADATA_REPOSITORY',
    ALBUM_REPOSITORY: 'ALBUM_REPOSITORY',
    USER_REPOSITORY: 'USER_REPOSITORY',
}